{% set version = "0.4.16" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-circlize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/circlize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/circlize/circlize_{{ version }}.tar.gz
  sha256: 16dc32c7704906d13a9e5281bb396e92fb89a6b17fa5e201953240726b650b67

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-globaloptions >=0.1.0
    - r-colorspace
    - r-shape
  run:
    - r-base
    - r-globaloptions >=0.1.0
    - r-colorspace
    - r-shape

test:
  commands:
    - $R -e "library('circlize')"           # [not win]
    - "\"%R%\" -e \"library('circlize')\""  # [win]

about:
  home: https://github.com/jokergoo/circlize, http://jokergoo.github.io/circlize_book/book/
  license: MIT
  summary: Circular layout is an efficient way for the visualization of huge  amounts of information. Here this package provides an implementation  of circular layout generation in R as well as an enhancement of available  software. The flexibility of the package is based on the usage of low-level  graphics functions such
    that self-defined high-level graphics can be easily  implemented by users for specific purposes. Together with the seamless  connection between the powerful computational and visual environment in R,  it gives users more convenience and freedom to design figures for  better understanding complex patterns behind multiple
    dimensional data.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: circlize
# Type: Package
# Title: Circular Visualization
# Version: 0.4.8
# Date: 2019-09-05
# Author: Zuguang Gu
# Maintainer: Zuguang Gu <z.gu@dkfz.de>
# Depends: R (>= 3.0.0), graphics
# Imports: GlobalOptions (>= 0.1.0), shape, grDevices, utils, stats, colorspace, methods, grid
# Suggests: knitr, dendextend (>= 1.0.1), ComplexHeatmap (>= 1.99.0), gridBase, png
# VignetteBuilder: knitr
# Description: Circular layout is an efficient way for the visualization of huge  amounts of information. Here this package provides an implementation  of circular layout generation in R as well as an enhancement of available  software. The flexibility of the package is based on the usage of low-level  graphics functions such that self-defined high-level graphics can be easily  implemented by users for specific purposes. Together with the seamless  connection between the powerful computational and visual environment in R,  it gives users more convenience and freedom to design figures for  better understanding complex patterns behind multiple dimensional data.
# URL: https://github.com/jokergoo/circlize, http://jokergoo.github.io/circlize_book/book/
# License: MIT + file LICENSE
# NeedsCompilation: no
# Packaged: 2019-09-06 12:55:48 UTC; jokergoo
# Repository: CRAN
# Date/Publication: 2019-09-08 10:00:02 UTC
