{% set version = "0.4.7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-circlize
  version: {{ version|replace("-", "_") }}

source:
  fn: circlize_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/circlize_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/circlize/circlize_{{ version }}.tar.gz
  sha256: 755cd4accf5b95e66a9307a82248043f511b6091e5f9412817ff523d215bc11f

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-globaloptions >=0.0.12
    - r-colorspace
    - r-shape

  run:
    - r-base
    - r-globaloptions >=0.0.12
    - r-colorspace
    - r-shape

test:
  commands:
    - $R -e "library('circlize')"  # [not win]
    - "\"%R%\" -e \"library('circlize')\""  # [win]

about:
  home: https://github.com/jokergoo/circlize, http://jokergoo.github.io/circlize_book/book/
  license: GPL (>= 2)
  summary: Circular layout is an efficient way for the visualization of huge  amounts of information.
    Here this package provides an implementation  of circular layout generation in R
    as well as an enhancement of available  software. The flexibility of the package
    is based on the usage of low-level  graphics functions such that self-defined high-level
    graphics can be easily  implemented by users for specific purposes. Together with
    the seamless  connection between the powerful computational and visual environment
    in R,  it gives users more convenience and freedom to design figures for  better
    understanding complex patterns behind multiple dimensional data.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
