travis:
  secure:
    BINSTAR_TOKEN: E4sYWa6LJgB5OXzrDT9BmkMiNjd0U21H82ZjyjO5vM4xUPzYHZQk0mhIAntZaGm9vlKrVsMenwoENsE4eb/F1EJTurSAJbQKEi0siLjxy2gfGzCFyupiFPzjtorbyfJiOyNcwsjgpIjw4u+IR42zAbcOz2++FWOIeLdqJbU7yP3tvGIS97tLnNCb+clUoc7iMk6LpIE+X0kZGBVZ6NwMKBsPQzPE6Wjus2B1wdlj0GoA2IUwagnipooyQrti4uVEIjm9s4NaJ4lmpGT1bjN3eDqdnWM5dg4IC8OVQt9UhVL5vbc5tIiJrB2TP7MB8rV7tL7OTpUF6mLkPLtdkl+3XywBcnoMxwNwQ77WkWN//KUtS0htHaUYVqM22kLCFPBVylN6q1O+RDl2opN98yHp+cbV2wuyojkZuuMd8DA/dQsZ7kv7Lctqx/uEMxg61M+LIDUt5ouqOnn3k53nu4oEp84w06InzhL7rac6DOLGn5cgs3odSLYE7WEx/4nXiznHgnSFvuQ11P5lAxvPA2faodYUQRCCCZKBHVUKaW48KL7jttwDS0k51lBwSx5mOCzirK1h9xwIwf2d6AwvU6aJpbhuFNTQHr8En1tTePUNOMUktPbPkVDhDzJCHJ7LMbFVa3Xcyv6arpettx1tW9991LN22nlPkOGBvdNTBPB1TvM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
